// Render FreeRADIUS clients.conf from the configured NAS shared secret.
//
// Stock FreeRADIUS only trusts localhost, so the MikroTik router (a different IP)
// is rejected with "Ignoring request from unknown client". We rewrite clients.conf
// at boot (db-init, before radiusd starts) so the router — and any LAN NAS — is
// accepted using the same shared secret the rest of the system already uses (the
// value autoconfig sets on the router and that CoA signs with).
//
// The accepted source range defaults to "everything": this is a single-tenant LAN
// appliance and the shared secret is the real gate. Scope it to the hotspot subnet
// with TIKSPOT_RADIUS_CLIENT_NET / _NET6 if you prefer a tighter bound.

import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { ensureNasSecret } from './nas.js';

const RADDB_DIR = process.env.TIKSPOT_RADDB_DIR ?? '/etc/raddb';
const CLIENT_NET = process.env.TIKSPOT_RADIUS_CLIENT_NET ?? '0.0.0.0/0';
const CLIENT_NET6 = process.env.TIKSPOT_RADIUS_CLIENT_NET6 ?? '::/0';

function block(name, addrLine, secret) {
  return `client ${name} {\n\t${addrLine}\n\tsecret = ${secret}\n\tproto = *\n}\n`;
}

export function renderClientsConf(secret) {
  return (
    '# Generated by Tikspot at boot — do not edit (regenerated on every start).\n' +
    '# Trusts localhost plus the configured LAN range, all using the NAS secret.\n' +
    '# More-specific localhost entries win for loopback; the /0 client catches the rest.\n' +
    block('localhost', 'ipaddr = 127.0.0.1', secret) +
    block('localhost_ipv6', 'ipv6addr = ::1', secret) +
    block('tikspot_net', `ipaddr = ${CLIENT_NET}`, secret) +
    block('tikspot_net6', `ipv6addr = ${CLIENT_NET6}`, secret)
  );
}

// Write clients.conf if the raddb dir exists (i.e. inside the container). Returns
// true if written, false where FreeRADIUS isn't installed — so db-init stays
// usable in plain dev/test environments without a raddb tree.
export function writeClientsConf(secret) {
  if (!secret) return false;
  if (!fs.existsSync(RADDB_DIR)) return false;
  fs.writeFileSync(path.join(RADDB_DIR, 'clients.conf'), renderClientsConf(secret));
  return true;
}

// Run one command with a hard timeout, resolving to its exit code (or null when
// the binary is missing / it timed out). Async on purpose: spawnSync blocked the
// event loop for up to 5s on every secret save, stalling every other request.
// A missing binary surfaces as an 'error' EVENT, not a throw — handle both.
export function runOnce(bin, args, timeoutMs = 5000) {
  return new Promise((resolve) => {
    let child;
    let done = false;
    const finish = (code) => {
      if (done) return;
      done = true;
      resolve(code);
    };
    try {
      child = spawn(bin, args, { stdio: 'ignore', timeout: timeoutMs });
    } catch {
      finish(null);
      return;
    }
    child.on('error', () => finish(null));
    child.on('exit', (code) => finish(code));
    // Belt and braces: spawn's own `timeout` kills the child, but if it never
    // starts we still want to give up.
    const t = setTimeout(() => {
      try { child.kill(); } catch { /* already gone */ }
      finish(null);
    }, timeoutMs + 500);
    if (typeof t.unref === 'function') t.unref();
  });
}

// Restart radiusd so a freshly-written clients.conf takes effect. FreeRADIUS does
// NOT reload client/secret definitions on SIGHUP, so we bounce the supervised
// longrun: SIGTERM, which the s6 supervisor follows by restarting it (the wanted
// state stays "up"). No-op where s6 isn't present (dev/test). Resolves true on a
// clean signal.
export async function reloadRadiusd() {
  for (const bin of ['/command/s6-svc', 's6-svc']) {
    const code = await runOnce(bin, ['-t', '/run/service/radiusd'], 5000);
    if (code === 0) return true;
  }
  return false;
}

// Re-render clients.conf from the current NAS secret and reload radiusd, so a
// secret set/changed at runtime (e.g. via the setup wizard or Auto-configure)
// takes effect live — keeping the container's accepted secret in lock-step with
// what the router was told, without needing a container restart.
//
// `wrote:false` just means there is no raddb tree (plain dev/test) — only
// `wrote && !reloaded` is a real problem worth warning the operator about.
export async function applyNasSecret(db) {
  const wrote = writeClientsConf(ensureNasSecret(db));
  const reloaded = wrote ? await reloadRadiusd() : false;
  return { wrote, reloaded, degraded: wrote && !reloaded };
}
